version: 2.1

default_job_params: &default_job_params
  docker:
    - image: circleci/node:10.16-browsers
  working_directory: ~/mapbox-gl-js

jobs:
  Installation:
    <<: *default_job_params
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "yarn.lock" }}
      - run: yarn --frozen-lockfile
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/mapbox-gl-js
          paths:
            - ./
  Unit Tests:
    <<: *default_job_params
    steps:
      - attach_workspace:
          at: .
      - run: yarn run test-unit
  Integration Tests:
    <<: *default_job_params
    steps:
      - attach_workspace:
          at: .
      - run: yarn run test-render
      - store_artifacts:
          path: "test/integration/render-tests/index.html"
      - run: yarn run test-query
      - store_test_results:
          path: test/integration/query-tests
      - store_artifacts:
          path: "test/integration/query-tests/index.html"
  Static Analysis:
    <<: *default_job_params
    steps:
      - attach_workspace:
          at: .
      - run: yarn run lint
      - run: yarn run lint-docs
      - run: yarn run lint-css
      - run: yarn run test-flow
      - run: yarn run test-expressions
  Build:
    <<: *default_job_params
    steps:
      - attach_workspace:
          at: .
      - run: yarn run build-prod-min
      - run: yarn run build-prod
      - run: yarn run build-csp
      - run: yarn run build-dev
      - run: yarn run build-css
      - run: yarn run build-style-spec
      - run: yarn run build-flow-types
      - run: yarn run test-build
      - store_artifacts:
          path: "dist"
      - store_artifacts:
          path: "test/release"
      - run:
          name: Check bundle size
          command: |
            node build/check-bundle-size.js "dist/mapbox-gl.js" "JS"
            node build/check-bundle-size.js "dist/mapbox-gl.css" "CSS"
      - run:
          name: Build
          command: BENCHMARK_VERSION="${CIRCLE_TAG:-$CIRCLE_BRANCH} $(git rev-parse --short=7 HEAD)" yarn run build-benchmarks

workflows:
  version: 2
  Our Awesome Workflow:
    jobs:
      - Installation
      # - Unit Tests:
      #     requires:
      #       - Installation
      # - Integration Tests:
      #     requires:
      #       - Installation
      # - Static Analysis:
      #     requires:
      #       - Installation
      # - Build:
      #     requires:
      #       - Installation
